---
title: "Taller-2"
author: "Eddy Herrera Daza"
date: "6 de septiembre de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Interpolación Polinómica

Se instalaran los paquetes Matrix y PolynomF

```{r, echo=T}
library(Matrix)
library(PolynomF)
```


1. Considere el comportamiento de gases no ideales se describe a menudo con la ecuación virial de estado. los siguientes datos para el nitrógeno $N_{2}$

```{r , echo=T}
T = c(100,200,300,400,500,600)
B = c(-160,-35,-4.2,9,16.9,21.3)
 plot(T,B, pch=19, cex=1, col = "red", asp=1,xlab="T", ylab="B", main="Comportamiento del N2 ")


```

Para el ajuste Polinómico se debe utilizar los seis puntos, para obtener un polinomio de grado 5 o menor que 5
```{r,echo=T}
DatosT = T[0:5]; DatosB = B[0:5]
 Ajuste_Polinomio = poly.calc(DatosT,DatosB)
 Ajuste_Polinomio
 -520.1 + 5.406917*450 - 0.02174708*450^2 + 3.955833e-05*450^3 -  
2.679167e-08*450^4 
 
```
```{r,echo=T}
plot(T,B, pch=19, cex=1, col = "red", asp=1,xlab="T", ylab="B", main="Comportamiento del N2 ")
curve(Ajuste_Polinomio,add=T,col = "blue",lty=1, lwd=1)
```
```{r}
DatosT = T[1:5]; DatosB = B[1:5]
 Ajuste_Polinomio1 = poly.calc(DatosT,DatosB)
 Ajuste_Polinomio1
 -520.1 + 5.406917*450 - 0.02174708*450^2 + 3.955833e-05*450^3 -  
2.679167e-08*450^4 
```
##Forma Baricentrica de Lagrange
```{r}
library(pracma)
barylag(DatosT,DatosB,450)
```

